[package]
name = "prefix-trie"
version = "0.2.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tiborschneider/prefix-trie"
homepage = "https://github.com/tiborschneider/prefix-trie"
documentation = "https://docs.rs/prefix-trie"
readme = "Readme.md"
categories = ["network-programming"]
keywords = ["IP", "prefix", "trie", "collection"]
description = "Prefix trie datastructure (both a set and a map) that provides exact and longest-prefix matches."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bench]]
name = "benchmark"
harness = false

[features]
serde = ["dep:serde"]

[dependencies]
ipnet = "2.6.0"
num-traits = "0.2.15"
take_mut = "0.2.2"
serde = { version = "1", optional = true}

[dev-dependencies]
criterion = "0.4.0"
paste = "1.0.10"
pretty_assertions = "1.3.0"
rand = "0.8.5"
