name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Cinstrument-coverage"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install tolls
      run: rustup component add llvm-tools-preview
      run: cargo install grcov
      run: LLVM_PROFILE_FILE="your_name-%p-%m.profraw" cargo test --verbose
    - name: test
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Generate coverage report
      run: ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
    - name: Upload coverage
      run: bash <(curl -s https://codecov.io/bash) -f lcov.info

